### PR TITLE
WWATCH-17 - Magento Staging module compatibility

### LINKED ISSUE #7: Parent Id incorrect in \DataFeedWatch\Connector\Plugin\ParentIds::getExtensionData
In \DataFeedWatch\Connector\Plugin\ParentIds::getExtensionData..

Currently this is getting the incorrect parent id. 

This looks at catalog_product_relation to get the parent id of said product. The catalog_product_relation.parent_id then needs to be joined on catalog_product_entity.row_id to get the actual parent id which is catalog_product_entity.parent_id.

### PR DESCRIPTION
**Pull request by wmwnuk**
This fixes #7

### CODE REVIEW

**Comment by SergeyOvseychick** [comment]
Hi everyone.
Could you please tell, when the changes will be added to release?
I have the latest 3.3.0 module version installed, but this fix is not present.
Thanks, Sergey

File: Plugin/ParentIds.php [hunk 1]
```diff
@@ -45,14 +65,28 @@ protected function getExtensionData(Product $product)
...
+                ->getConnection()
+                ->select()
+                ->from($tableName, 'parent_id')
+                ->where(sprintf('child_id = %s', $product->getId()));
 
-        return $connection->fetchCol($query);
+            return $connection->fetchCol($query);
+        } else {
+            $query = $connection->select()
+                ->from(['r' => $tableName], 'parent_id')
```
Comment (derekBaldwinGG) [inline Plugin/ParentIds.php:80]: I had to change this line to not select any cols from r (relations table) and only select parent_id from the entity table.
`->from(['r' => $tableName], '')`

**Comment by derekBaldwinGG** [comment]
> Hi everyone. Could you please tell, when the changes will be added to release? I have the latest 3.3.0 module version installed, but this fix is not present. Thanks, Sergey

@SergeyOvseychick in case you didn't know it's in the 'dev-master' version but I know that's not an official new version.

File: Plugin/ParentIds.php (hunk 1 above)
Comment (wpsamurai) [reply Plugin/ParentIds.php:80]: Thanks @derekBaldwinGG for sharing. @wmwnuk could you please have a look at this?

Comment (wpsamurai) [reply Plugin/ParentIds.php:80]: Good catch @derekBaldwinGG. We added this change (https://github.com/datafeedwatch/dfwconnector-magento2/pull/12) to the code.
